# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Minecraft server'
  vmImage: ubuntu-latest

variables:
  location: 'westeurope'
  resource-group: 'az-400'
  templateFile: '.azure/bicep/Function.bicep'
  subscriptionid: '8ed210d1-9420-4e71-968d-a73398093c77'
  azureserviceconnection: 'azureConnection'
  appName: 'webapp'
  storageAccountName: 'storage'

stages:
  # - stage:
  #   variables:
  #     - group: mygroup-test
  #   displayName: 'test'
  #   jobs:
  #     - job:
  #       steps:
  #         - script: echo 'Hello az 400 Tuesday'
  #           displayName: 'Executing echo command'
  #         - task: AzureCLI@2
  #           displayName: 'Creating the resource group'
  #           inputs:
  #             azureSubscription: azureConnection
  #             scriptType: pscore
  #             scriptLocation: inlineScript
  #             inlineScript: |
  #               az group create --location $(location) --name $(resourceGroupName)
  - stage: Build
    displayName: Build .Net Core Solution
    jobs:
    - job: Build
      steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: 'restore'
          projects: '**/*.sln'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: '**/*.sln'                

  - stage: Deploy
    displayName: Creating and Deploying function
    jobs:
      - job: Create
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: Deploy App Service Plan Bicep
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(azureserviceconnection)'
            subscriptionId: '$(subscriptionid)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(resource-group)'
            location: '$(location)'
            templateLocation: 'Linked artifact'
            csmFile: '$(templateFile)'
            overrideParameters: '-appName $(appname) -location $(location) -storageAccountName $(storageaccountname)'
            deploymentMode: 'Incremental'
            deploymentOutputs: 'asp-json'
    


#  - stage:
#    displayName: 'prod'
#    variables:
#      - group: mygroup-prod
#    jobs:
#      - job:
#        steps:
#          - script: echo 'Hello az 400 Tuesday'
#            displayName: 'Executing echo command'
#          - task: AzureCLI@2
#            displayName: 'Creating the resource group'
#            inputs:
#              azureSubscription: azureConnection
#              scriptType: pscore
#              scriptLocation: inlineScript
#              inlineScript: |
#                az group create --location $(location) --name $(resourceGroupName)
