#This pipeline will create resource group and needed resources within
#Then checkout, restore, build and deploy a Function App

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .ado
      - .azure
      
variables:
  - group: 'Function-App-Prod'
  
  - name: templateFile
    value: '.azure/bicep/Environment.bicep'

  - name: azureServiceConnection
    value: 'azureConnection'

pool:
  name: 'Minecraft server'
  vmImage: 'ubuntu-latest'

stages:
  - stage:
    #Setup or update environment
    displayName: Create or update environment
    variables:
      - group: 'Function-App-Prod'
    jobs:
      - job:
        condition: false #prevents this stage to run
        steps:
          - checkout: none
          - task: AzureCLI@2
            displayName: Create or update the resource group
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az group create --location $(location) --name $(resourceGroupName)

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Create or update environment
            inputs:
              addSpnToEnvironment: true
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(azureServiceConnection)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupName)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(templateFile)'
              overrideParameters: '-appName $(appname) -location $(location) -storageAccountName $(storageaccountname)'
              deploymentMode: 'Incremental'
              deploymentOutputs: 'asp-json'
