#This pipeline will create resource group and needed resources within
#Then checkout, restore, build and deploy a Function App

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Functions
      
variables:
  - group: 'Production Variables'
  
  - name: serviceConnection
    value: 'azureConnection'

  - name: appname
    value: 'functions$(suffix)'

  - name: storageAccountName
    value: 'storage$(suffix)'

pool:
  name: 'Minecraft server'
  vmImage: 'ubuntu-latest'

stages:
  - stage:
    #Checkout, restore, build and deploy the function app
    displayName: Build & Deploy
    jobs:
      - job:
        steps:
        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: 'restore'
            projects: 'Functions/**/*.csproj'
            feedsToUse: 'select'

#        - task: DotNetCoreCLI@2
#          displayName: Build 
#          inputs:
#            command: 'build'
#            projects: 'Functions/**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'Build and Publish'
          inputs:
            command: 'publish'
            projects: 'Functions/**/*.csproj'
            publishWebProjects: false
            arguments: "-o $(Build.ArtifactStagingDirectory) --configuration Release"

        - task: PublishPipelineArtifact@1 
          displayName: 'Publish artifact'
          inputs: 
            targetPath: "$(Build.ArtifactStagingDirectory)"
            artifact: WebApp
            publishLocation: "pipeline"

  - template: Deploy.yaml
    parameters:
      Environment: Test
      AppName: functions010572
      AppType: functionApp
      xwConnection: $(serviceConnection)