trigger:
  branches:
    include:
      - main
  paths:
    include:
      - WebApp
      
variables:
  - group: 'Production Variables'
  
  - name: serviceConnection
    value: 'azureConnection'
    
  - name: appname
    value: 'web$(suffix)'

pool:
  name: 'Minecraft server'
  vmImage: 'ubuntu-latest'

stages:
  - stage:
    displayName: Build & Deploy
    jobs:
      - job:
        steps:
        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: 'restore'
            projects: 'WebApp/**/*.csproj'
            feedsToUse: 'select'

        - task: DotNetCoreCLI@2
          displayName: 'Build and Publish'
          inputs:
            command: 'publish'
            projects: 'WebApp/**/*.csproj'
            publishWebProjects: false
            arguments: "-o $(Build.ArtifactStagingDirectory) --configuration Release"
  
        - task: PublishPipelineArtifact@1 
          displayName: 'Publish artifact'
          inputs: 
            targetPath: "$(Build.ArtifactStagingDirectory)"
            artifact: $(appName)
            publishLocation: "pipeline"
  
#  - template: Deploy.yaml
#    parameters:
#      Environment: Test
#      AppName: $(appName)
#      AppType: webApp
#      ServiceConnection: $(serviceConnection)