# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Minecraft server'
  vmImage: ubuntu-latest

variables:
  - name: location
    value: 'westeurope'

stages:
  - stage:
    variables:
      - group: mygroup-test
    displayName: 'test'
    jobs:
      - job:
        steps:
          - script: echo 'Hello az 400 Tuesday'
            displayName: 'Executing echo command'
          - task: AzureCLI@2
            displayName: 'Creating the resource group'
            inputs:
              azureSubscription: azureConnection
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az group create --location $(location) --name $(resourceGroupName)
  - stage:
    displayName: 'prod'
    variables:
      - group: mygroup-prod
    jobs:
      - job:
        steps:
          - script: echo 'Hello az 400 Tuesday'
            displayName: 'Executing echo command'
          - task: AzureCLI@2
            displayName: 'Creating the resource group'
            inputs:
              azureSubscription: azureConnection
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az group create --location $(location) --name $(resourceGroupName)
