# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Minecraft server'
  vmImage: ubuntu-latest

variables:
  - name: location
    value: 'westeurope'

stages:
  - stage:
    variables:
      - group: mygroup-test
    displayName: 'test'
    jobs:
      - job:
        steps:
          - script: echo 'Hello az 400 Tuesday'
            displayName: 'Executing echo command'
          - task: AzureCLI@2
            displayName: 'Creating the resource group'
            inputs:
              azureSubscription: azureConnection
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az group create --location $(location) --name $(resourceGroupName)


  - stage: Build
    displayName: Build .Net Core Solution
    jobs:
    - job: Build
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: 'restore'
          projects: '**/*.sln'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: '**/*.sln'
      
#      - task: DotNetCoreCLI@2
#        displayName: Test
#        inputs:
#          command: 'test'
#          projects: 'tests/UnitTests/*.csproj'
      
#      - task: DotNetCoreCLI@2
#        displayName: Publish
#        inputs:
#          command: 'publish'
#          publishWebProjects: true
#          arguments: '-o $(Build.ArtifactStagingDirectory)'
      
#      - task: PublishBuildArtifacts@1
#        displayName: Publish Artifacts ADO - Website
#        inputs:
#          pathToPublish: '$(Build.ArtifactStagingDirectory)'
#          artifactName: Website
      
#      - task: PublishBuildArtifacts@1
#        displayName: Publish Artifacts ADO - Bicep
#        inputs:
#          PathtoPublish: '$(Build.SourcesDirectory)/.azure/bicep/webapp.bicep'
#          ArtifactName: 'Bicep'
#          publishLocation: 'Container'
#  - stage:
#    displayName: 'prod'
#    variables:
#      - group: mygroup-prod
#    jobs:
#      - job:
#        steps:
#          - script: echo 'Hello az 400 Tuesday'
#            displayName: 'Executing echo command'
#          - task: AzureCLI@2
#            displayName: 'Creating the resource group'
#            inputs:
#              azureSubscription: azureConnection
#              scriptType: pscore
#              scriptLocation: inlineScript
#              inlineScript: |
#                az group create --location $(location) --name $(resourceGroupName)

